apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: python
  name: python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - image: m19142/python-app
        name: python
        volumeMounts:
        - mountPath: /var/python-app
          name: python-data-mount
      volumes:
      - name: python-data-mount
        persistentVolumeClaim:
          claimName: python-data   